version: '3'
services:
  tesis:
    build:
        dockerfile: ./Dockerfile
    image: jupyter/scipy-notebook
    volumes:
        - /c/Users/edwin.hurtado/Proyectos/Universidad/Maestria/trozos:/tmp/data
    ports:
    - 8888:8888
    
volumes:
     app-volume: 
  

