version: '3'
services:
  tesis:
    build:
        dockerfile: ./Dockerfile
    image: jupyter/scipy-notebook
    volumes:
        - app-volume:/c/Users/edwin.hurtado/Proyectos/Universidad/Maestria/trozos/temp:/home/jovyan/
    ports:
    - 8888:8888
    
volumes:
     app-volume:
        driver: local
  

